inputs:
- {file: /home/cory/projects/online_journal/submissions_staging/1_Middlelost_PartOne2.pdf,
  format: double}
- {file: /home/cory/projects/online_journal/submissions_staging/2_Bonnie_Melton_Layout_for_PDF.pdf,
  format: single}
- {file: /home/cory/projects/online_journal/submissions_staging/3_Middlelost1.1PartTwo.pdf,
  format: double}
- {file: /home/cory/projects/online_journal/submissions_staging/4_Miracles.pdf, format: single}
- {file: /home/cory/projects/online_journal/submissions_staging/5_Middlelost_1.1_Part_Three.pdf,
  format: double}
output_directory: /home/cory/projects/online_journal/app/static/issues/2
title: Issue 2
cover: issues/test/0.png
